version: "3.7"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - ./html/:/var/www/html/
    ports:
      - 8080:80
    depends_on:
      - db

  db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app1
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - 8081:80

  adminer:
    image: adminer:4.7.7
    restart: always
    ports:
      - 8082:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes:
  mysql-data:
